### ISSUE TITLE
Image ratio

### ISSUE THREAD

**Issue by kl0x** [Excolo/Excolo-Slider#32]
For some reason I'm not able to keep the original ratio of the slides, it always covers the whole space so tall images are horrible.

I need css height 100% and width:auto.

Is there anyway of doing this? 

thx in advance
![f](https://cloud.githubusercontent.com/assets/15238950/10651183/51ef3ed2-784e-11e5-8ec8-ed4aab059c55.png)
![f1](https://cloud.githubusercontent.com/assets/15238950/10651222/8c49d83a-784e-11e5-8409-bbe8a4ebd369.png)

**Comment by Excolo** [comment]
Can you create an example of your issue in a jsfiddle or similar? Then I'll have a look. It might just be a matter of tweaking the stylesheet slightly. It's been a while since I've worked on this project.

**Comment by kl0x** [comment]
Default everything.
http://jsfiddle.net/kl0x/ukL20593/

**Comment by Excolo** [comment]
Thank you. Excolo-Slider basically works by turning every child element of the slide container, into a slide. So you could do it by wrapping your image in a <div> container (which would then become the slide) and set height 100% and width auto on the <img> itself. It's a bit of a hack, but it's been too long since I've worked on the code, for me to start working a solution into it right now. 

I've updated your fiddle with my solution: http://jsfiddle.net/Excolo/ukL20593/1/

Hope this helps.
- Nikolaj
