### ISSUE TITLE
Link slide to Mysql

### ISSUE THREAD

**Issue by amanyel** [Excolo/Excolo-Slider#33]
Hi
I would to ask if i can select a image from my mysql using php and display using excolo-slider how i will do it 
Thank you in advance

**Comment by Excolo** [comment]
Hello

This is actually more related to PHP than to the slider. The way to show an image from mysql using php, is the same whether you use the image in my slider, or just show it as a regular image on a webpage.
So I guess the way you would do it, is to have a PHP webpage return the image data along with mime type of the image, and then just add the url to that PHP endpoint in the href attribute of a regular image element. 
The only thing the excolo-slider really does, is move the html image elements (or any html element really) around behind a masking div container. So whether the image comes from a database or is loaded as static content shouldn't matter. :-)

It's been years since I did any professional work in PHP, so I'm afraid I can't get you any examples of how to make a PHP webpage return the image data with the mime type as content header, but I'm certain there'll be a lot of good resources out there that can help with that. 
A quick google search suggests that you could get PHP to return an image using the following code:
<?php $id = (isset($_GET['id']) && is_numeric($_GET['id'])) ? intval($_GET['id']) : 0; $image = getImageFromDatabase($id); // your code to fetch the image header('Content-Type: image/jpeg'); echo $image; ?>
On 29-04-2016 20:52:17, Amany EL Romeh <notifications@github.com> wrote:
Hi
I would to ask if i can select a image from my mysql using php and display using excolo-slider how i will do it
Thank you in advance

**Comment by amanyel** [comment]
okay i will search it and thank you for your advice and reply
Sincerely

**Comment by Excolo** [comment]
No problem. Feel free to contact me should you have any issues finding a solution. 

Have a nice weekend.
Best regards
- Nikolaj
On 29-04-2016 21:55:03, Amany EL Romeh <notifications@github.com> wrote:
okay i will search it and thank you for your advice and reply
Sincerely
